package mapping

import (
	"github.com/awslabs/ar-go-tools/fake/analysis"
	"golang.org/x/tools/go/ssa"
)

type SpecialHandlerFunc func(funs []*ssa.Function, mapping map[string][]analysis.ConditionalCapability)

var specialHandlersInOrder = []struct {
	name string
	fn   SpecialHandlerFunc
}{
	{name: "fcntl", fn: Handler_fcntl},
	{name: "ioctl", fn: Handler_ioctl},
	// {name: "write", fn: Handler_write},
	// {name: "socket", fn: Handler_socket},
	// {name: "timerfd_create", fn: Handler_timerfd_create},
	// {name: "linkat", fn: Handler_linkat},
	// {name: "setgroups", fn: Handler_setgroups},
	// {name: "clone", fn: Handler_clone},
	// {name: "clock_nanosleep", fn: Handler_clock_nanosleep},
	// {name: "iopl", fn: Handler_iopl},
	// {name: "reboot", fn: Handler_reboot},
	// {name: "sethostname", fn: Handler_sethostname},
	// {name: "setdomainname", fn: Handler_setdomainname},
	// {name: "kexec_load", fn: Handler_kexec_load},
	// {name: "kexec_file_load", fn: Handler_kexec_file_load},
	// {name: "delete_module", fn: Handler_delete_module},
	// {name: "setgid", fn: Handler_setgid},
	// {name: "setregid", fn: Handler_setregid},
	// {name: "setfsgid", fn: Handler_setfsgid},
	// {name: "prlimit64", fn: Handler_prlimit64},
	// {name: "bind", fn: Handler_bind},
	// {name: "timerfd_settime", fn: Handler_timerfd_settime},
	// {name: "setuid", fn: Handler_setuid},
	// {name: "setreuid", fn: Handler_setreuid},
	// {name: "setresuid", fn: Handler_setresuid},
	// {name: "setfsuid", fn: Handler_setfsuid},
	// {name: "caif_create", fn: Handler_caif_create},
	// {name: "HDIO_DRIVE_CMD", fn: Handler_HDIO_DRIVE_CMD},
	// {name: "isst_if_mbox_proc_cmd", fn: Handler_isst_if_mbox_proc_cmd},
	// {name: "mlx5_ib_devx_create", fn: Handler_mlx5_ib_devx_create},
	// {name: "rtc_ioctl", fn: Handler_rtc_ioctl},
	// {name: "scsi_ioctl_reset", fn: Handler_scsi_ioctl_reset},
	// {name: "sg_proc_write_dressz", fn: Handler_sg_proc_write_dressz},
	// {name: "vidioc_s_fbuf", fn: Handler_vidioc_s_fbuf},
	// {name: "__blkdev_reread_part", fn: Handler___blkdev_reread_part},
	// {name: "__rfcomm_create_dev", fn: Handler___rfcomm_create_dev},
	// {name: "__rfcomm_release_dev", fn: Handler___rfcomm_release_dev},
	// {name: "__sock_cmsg_send", fn: Handler___sock_cmsg_send},
	// {name: "acct", fn: Handler_acct},
	// {name: "addrconf_add_ifaddr", fn: Handler_addrconf_add_ifaddr},
	// {name: "airo_get_aplist", fn: Handler_airo_get_aplist},
	// {name: "arcmsr_sysfs_iop_message_write", fn: Handler_arcmsr_sysfs_iop_message_write},
	// {name: "arp_ioctl", fn: Handler_arp_ioctl},
	// {name: "atm_mpoa_ioctl", fn: Handler_atm_mpoa_ioctl},
	// {name: "audit_bind", fn: Handler_audit_bind},
	// {name: "blkdev_report_zones_ioctl", fn: Handler_blkdev_report_zones_ioctl},
	// {name: "blkdev_reset_zones_ioctl", fn: Handler_blkdev_reset_zones_ioctl},
	// {name: "bpf", fn: Handler_bpf},
	// {name: "bpf_map_get_fd_by_id", fn: Handler_bpf_map_get_fd_by_id},
	// {name: "bpf_prog_get_fd_by_id", fn: Handler_bpf_prog_get_fd_by_id},
	// {name: "bpf_prog_load", fn: Handler_bpf_prog_load},
	// {name: "bpf_prog_test_run", fn: Handler_bpf_prog_test_run},
	// {name: "bpf_task_fd_query", fn: Handler_bpf_task_fd_query},
	// {name: "br_ioctl", fn: Handler_br_ioctl},
	// {name: "bttv_s_fbuf", fn: Handler_bttv_s_fbuf},
	// {name: "cachefiles_daemon_open", fn: Handler_cachefiles_daemon_open},
	// {name: "cacheflush", fn: Handler_cacheflush},
	// {name: "cdrom_ioctl_reset", fn: Handler_cdrom_ioctl_reset},
	// {name: "cgroup1_get_tree", fn: Handler_cgroup1_get_tree},
	// {name: "clip_ioctl", fn: Handler_clip_ioctl},
	// {name: "cobalt_cobaltc", fn: Handler_cobalt_cobaltc},
	// {name: "comedi_open", fn: Handler_comedi_open},
	// {name: "compat_do_arpt_set_ctl", fn: Handler_compat_do_arpt_set_ctl},
	// {name: "compat_do_ebt_set_ctl", fn: Handler_compat_do_ebt_set_ctl},
	// {name: "compat_do_ipt_get_ctl", fn: Handler_compat_do_ipt_get_ctl},
	// {name: "compat_do_ipt_set_ctl", fn: Handler_compat_do_ipt_set_ctl},
	// {name: "ctrl_cdev_ioctl", fn: Handler_ctrl_cdev_ioctl},
	// {name: "cxgb_extension_ioctl", fn: Handler_cxgb_extension_ioctl},
	// {name: "dasd_ioctl_format", fn: Handler_dasd_ioctl_format},
	// {name: "dasd_ioctl_set_ro", fn: Handler_dasd_ioctl_set_ro},
	// {name: "dasd_symm_io", fn: Handler_dasd_symm_io},
	// {name: "do_ipt_set_ctl", fn: Handler_do_ipt_set_ctl},
	// {name: "do_vm86_irq_handling", fn: Handler_do_vm86_irq_handling},
	// {name: "drm_legacy_addmap_ioctl", fn: Handler_drm_legacy_addmap_ioctl},
	// {name: "eeprom_read", fn: Handler_eeprom_read},
	// {name: "eni_ioctl", fn: Handler_eni_ioctl},
	// {name: "erofs_getxattr", fn: Handler_erofs_getxattr},
	// {name: "EXT2_IOC_SETVERSION", fn: Handler_EXT2_IOC_SETVERSION},
	// {name: "ext4_ioctl", fn: Handler_ext4_ioctl},
	// {name: "ext4_ioctl_setversion", fn: Handler_ext4_ioctl_setversion},
	// {name: "f2fs_ioc_defragment", fn: Handler_f2fs_ioc_defragment},
	// {name: "f2fs_ioc_flush_device", fn: Handler_f2fs_ioc_flush_device},
	// {name: "f2fs_ioc_fssetxattr", fn: Handler_f2fs_ioc_fssetxattr},
	// {name: "f2fs_ioc_gc_range", fn: Handler_f2fs_ioc_gc_range},
	// {name: "f2fs_ioc_resize_fs", fn: Handler_f2fs_ioc_resize_fs},
	// {name: "f2fs_ioc_setflags", fn: Handler_f2fs_ioc_setflags},
	// {name: "f2fs_ioc_shutdown", fn: Handler_f2fs_ioc_shutdown},
	// {name: "f2fs_ioc_start_atomic_write", fn: Handler_f2fs_ioc_start_atomic_write},
	// {name: "f2fs_setattr", fn: Handler_f2fs_setattr},
	// {name: "fanotify_init", fn: Handler_fanotify_init},
	// {name: "FITRIM", fn: Handler_FITRIM},
	// {name: "floppy_ioctl", fn: Handler_floppy_ioctl},
	// {name: "floppy_locked_ioctl", fn: Handler_floppy_locked_ioctl},
	// {name: "fore200e_setloop", fn: Handler_fore200e_setloop},
	// {name: "fscrypt_ioctl_remove_key_all_users", fn: Handler_fscrypt_ioctl_remove_key_all_users},
	// {name: "fstrim", fn: Handler_fstrim},
	// {name: "gelic_net_set_wol", fn: Handler_gelic_net_set_wol},
	// {name: "gsm_ioctl", fn: Handler_gsm_ioctl},
	// {name: "hci_sock_ioctl", fn: Handler_hci_sock_ioctl},
	// {name: "HDLCDRVCTL_SETMODEMPAR", fn: Handler_HDLCDRVCTL_SETMODEMPAR},
	// {name: "hpet_ioctl", fn: Handler_hpet_ioctl},
	// {name: "hpfs_ioctl", fn: Handler_hpfs_ioctl},
	// {name: "i915_gem_userptr_init__mmu_notifier", fn: Handler_i915_gem_userptr_init__mmu_notifier},
	// {name: "i915_perf_add_config_ioctl", fn: Handler_i915_perf_add_config_ioctl},
	// {name: "ioctl(FS_IOC_FSSETXATTR)", fn: Handler_ioctl_FS_IOC_FSSETXATTR},
	// {name: "ioperm", fn: Handler_ioperm},
	// {name: "ip_rt_ioctl", fn: Handler_ip_rt_ioctl},
	// {name: "ip6_mroute_setsockopt", fn: Handler_ip6_mroute_setsockopt},
	// {name: "ipoib_vlan_add", fn: Handler_ipoib_vlan_add},
	// {name: "ipoib_vlan_delete", fn: Handler_ipoib_vlan_delete},
	// {name: "ipr_write_dump", fn: Handler_ipr_write_dump},
	// {name: "ipv6_flowlabel_opt_get", fn: Handler_ipv6_flowlabel_opt_get},
	// {name: "ipv6_sock_ac_join", fn: Handler_ipv6_sock_ac_join},
	// {name: "isst_if_mmio_rd_wr", fn: Handler_isst_if_mmio_rd_wr},
	// {name: "isst_if_msr_cmd_req", fn: Handler_isst_if_msr_cmd_req},
	// {name: "jfs_ioctl", fn: Handler_jfs_ioctl},
	// {name: "jfs_listxattr", fn: Handler_jfs_listxattr},
	// {name: "kernel_move_pages", fn: Handler_kernel_move_pages},
	{name: "madvise", fn: Handler_madvise},
	// {name: "mbind", fn: Handler_mbind},
	// {name: "md_ioctl", fn: Handler_md_ioctl},
	// {name: "megadev_ioctl", fn: Handler_megadev_ioctl},
	// {name: "migrate_pages", fn: Handler_migrate_pages},
	// {name: "mincore", fn: Handler_mincore},
	// {name: "mkiss_open", fn: Handler_mkiss_open},
	// {name: "mlock", fn: Handler_mlock},
	// {name: "mlockall", fn: Handler_mlockall},
	// {name: "moxa_open", fn: Handler_moxa_open},
	// {name: "mtrr_ioctls", fn: Handler_mtrr_ioctls},
	// {name: "nice", fn: Handler_nice},
	// {name: "OCFS2_IOC_GROUP_EXTEND", fn: Handler_OCFS2_IOC_GROUP_EXTEND},
	// {name: "open_by_handle", fn: Handler_open_by_handle},
	// {name: "open_kcore", fn: Handler_open_kcore},
	// {name: "orinoco_ioctl_reset", fn: Handler_orinoco_ioctl_reset},
	// {name: "pci_read_config", fn: Handler_pci_read_config},
	// {name: "pciconfig_write", fn: Handler_pciconfig_write},
	// {name: "perf_event_open", fn: Handler_perf_event_open},
	// {name: "perf_event_query_prog_array", fn: Handler_perf_event_query_prog_array},
	// {name: "perf_write", fn: Handler_perf_write},
	// {name: "pgctrl_write", fn: Handler_pgctrl_write},
	// {name: "pidns_install", fn: Handler_pidns_install},
	// {name: "plip_ioctl", fn: Handler_plip_ioctl},
	// {name: "pm_wake_unlock", fn: Handler_pm_wake_unlock},
	// {name: "pmu_ioctl", fn: Handler_pmu_ioctl},
	// {name: "ppp_ioctl", fn: Handler_ppp_ioctl},
	// {name: "pppoatm_ioctl", fn: Handler_pppoatm_ioctl},
	// {name: "prctl", fn: Handler_prctl},
	// {name: "proc_bus_pci_mmap", fn: Handler_proc_bus_pci_mmap},
	// {name: "proc_bus_pci_read", fn: Handler_proc_bus_pci_read},
	// {name: "proc_do_static_key", fn: Handler_proc_do_static_key},
	// {name: "proc_dointvec_minmax_sysadmin", fn: Handler_proc_dointvec_minmax_sysadmin},
	// {name: "proc_sched_autogroup_set_nice", fn: Handler_proc_sched_autogroup_set_nice},
	// {name: "qib_get_user_pages", fn: Handler_qib_get_user_pages},
	// {name: "REISERFS_IOC_SETFLAGS", fn: Handler_REISERFS_IOC_SETFLAGS},
	// {name: "reset_rm2", fn: Handler_reset_rm2},
	// {name: "reuseport_array_alloc", fn: Handler_reuseport_array_alloc},
	// {name: "rio_ioctl", fn: Handler_rio_ioctl},
	// {name: "rtnetlink_bind", fn: Handler_rtnetlink_bind},
	// {name: "sbni_ioctl", fn: Handler_sbni_ioctl},
	// {name: "scc_ioctl", fn: Handler_scc_ioctl},
	// {name: "scif_bind", fn: Handler_scif_bind},
	// {name: "scsi_cmd_blk_ioctl", fn: Handler_scsi_cmd_blk_ioctl},
	// {name: "seccomp_get_filter", fn: Handler_seccomp_get_filter},
	// {name: "seccomp_get_metadata", fn: Handler_seccomp_get_metadata},
	// {name: "sed_ioctl", fn: Handler_sed_ioctl},
	// {name: "set_task_ioprio", fn: Handler_set_task_ioprio},
	// {name: "sg_proc_write_adio", fn: Handler_sg_proc_write_adio},
	// {name: "shmctl", fn: Handler_shmctl},
	// {name: "SIOCAX25ADDUID", fn: Handler_SIOCAX25ADDUID},
	// {name: "SIOCDELTUNNEL", fn: Handler_SIOCDELTUNNEL},
	// {name: "SIOCDEVENSLAVE", fn: Handler_SIOCDEVENSLAVE},
	// {name: "snapshot_ioctl", fn: Handler_snapshot_ioctl},
	// {name: "sock_diag_destroy", fn: Handler_sock_diag_destroy},
	// {name: "sock_hash_alloc", fn: Handler_sock_hash_alloc},
	// {name: "sock_setbindtodevice", fn: Handler_sock_setbindtodevice},
	// {name: "stack_map_alloc", fn: Handler_stack_map_alloc},
	// {name: "sysctl_numa_balancing", fn: Handler_sysctl_numa_balancing},
	// {name: "sysctl_schedstats", fn: Handler_sysctl_schedstats},
	// {name: "timerslack_ns_write", fn: Handler_timerslack_ns_write},
	// {name: "tioclinux", fn: Handler_tioclinux},
	// {name: "tiocsti", fn: Handler_tiocsti},
	// {name: "tun_set_iff", fn: Handler_tun_set_iff},
	// {name: "ubi_cdev_ioctl", fn: Handler_ubi_cdev_ioctl},
	// {name: "ubifs_ioctl", fn: Handler_ubifs_ioctl},
	// {name: "ubifs_listxattr", fn: Handler_ubifs_listxattr},
	// {name: "udf_ioctl", fn: Handler_udf_ioctl},
	// {name: "umount", fn: Handler_umount},
	// {name: "unshare_nsproxy_namespaces", fn: Handler_unshare_nsproxy_namespaces},
	// {name: "user_shm_lock", fn: Handler_user_shm_lock},
	// {name: "userfaultfd", fn: Handler_userfaultfd},
	// {name: "vfio_group_fops_open", fn: Handler_vfio_group_fops_open},
	// {name: "vfio_group_get_device_fd", fn: Handler_vfio_group_get_device_fd},
	// {name: "vfio_group_set_container", fn: Handler_vfio_group_set_container},
	// {name: "via_dma_init", fn: Handler_via_dma_init},
	// {name: "vivid_vid_cap_s_fbuf", fn: Handler_vivid_vid_cap_s_fbuf},
	// {name: "vol_cdev_ioctl", fn: Handler_vol_cdev_ioctl},
	// {name: "vt_compat_ioctl", fn: Handler_vt_compat_ioctl},
	// {name: "vt_do_kdgkb_ioctl", fn: Handler_vt_do_kdgkb_ioctl},
	// {name: "vt_do_kdsk_ioctl", fn: Handler_vt_do_kdsk_ioctl},
	// {name: "xfs_ioc_setlabel", fn: Handler_xfs_ioc_setlabel},
	// {name: "xfs_readlink_by_handle", fn: Handler_xfs_readlink_by_handle},
	// {name: "xfs_set_dmattrs", fn: Handler_xfs_set_dmattrs},
	// {name: "xsk_map_alloc", fn: Handler_xsk_map_alloc},
}

func RunAllSpecialHandlers(funs []*ssa.Function, mapping map[string][]analysis.ConditionalCapability) {
	if mapping == nil {
		return
	}
	for _, h := range specialHandlersInOrder {
		h.fn(funs, mapping)
	}
}

func RunSpecialHandlerForSyscall(syscall string, funs []*ssa.Function, mapping map[string][]analysis.ConditionalCapability) bool {
	if mapping == nil {
		return false
	}
	for _, h := range specialHandlersInOrder {
		if h.name == syscall {
			h.fn(funs, mapping)
			return true
		}
	}
	return false
}
